### ISSUE TITLE
Jupyter kernel bug when mixing const and not const

### ISSUE THREAD

**Issue by drewrobson** [root-mirror/cling#282]
I'm seeing buggy behavior in the Jupyter kernel that comes with cling when mixing `const` and not `const`. Run the following in a cell...
```
int x = 1;
const int y = x;
const int z = y;
```
... and then run this in a new cell:
```
z
```
I get 0 instead of 1. WAT?

xeus-cling has the same [issue](https://github.com/QuantStack/xeus-cling/issues/216). OTOH, [merging both cells](https://gist.github.com/drewrobson/d2a9cc61b5821c94648e317ce555efb3), rearranging the `const` modifiers, or pasting `int x = 1; const int y = x; const int z = y;` (return) followed by `z` (return) into cling in a terminal all work fine.

It just isn't C++ if you can't sprinkle `const` all over the place. :smiley:

**Comment by Axel-Naumann** [comment]
Can you confirm that this is fixed in the current master?

**Comment by drewrobson** [comment]
I just retested, and based on my understanding this is still broken in the current master. I compiled a new Debug build from source by following the instructions at https://root.cern.ch/cling-build-instructions. I believe this should build the current master?

**Comment by Axel-Naumann** [comment]
Yes thanks that should be the current master. I'll need to debug this; it's indeed very strange that this doesn't show up in cling's prompt or ROOT's Jupyter interface, but only (xeus-)cling's Jupyter interface...
